name: WaterTracker
options:
  bundleIdPrefix: com.ketao
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  WaterTracker:
    type: application
    platform: iOS
    sources:
      - path: WaterTracker
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: WaterTracker/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ketao.WaterTracker
        PRODUCT_NAME: WaterTracker
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: WaterTrackerWatch
        embed: true
      - target: WaterTrackerWidgets
        embed: true

  WaterTrackerWatch:
    type: application
    platform: watchOS
    sources:
      - path: WaterTrackerWatch
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: WaterTrackerWatch/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ketao.WaterTracker.watchkitapp
        PRODUCT_NAME: WaterTracker Watch App
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  WaterTrackerWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: WaterTrackerWidgets
      - path: Shared
    settings:
      base:
        INFOPLIST_FILE: WaterTrackerWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ketao.WaterTracker.widgets
        PRODUCT_NAME: WaterTrackerWidgets
